### PR TITLE
fix incorrect context in actual use

### PR DESCRIPTION
**Pull request by jrit**
@Tathanen though that appeared to work because tests passed, in actual use, `this` was undefined, so this fixes that.

### CODE REVIEW

**Comment by Tathanen** [comment]
Did you fix whatever was false-passing those tests then?

This is also breaking, are you gonna re-release v5 with it or go v6?

Update the doc too, since you've changed the queryUrl function signature.

**Comment by jrit** [comment]
I'm going to release 5.0.1 - 5.0.0 is broken and unusable so a bump to 6.0.0 is pointless.

The tests are updated for how it works now, which won't be revertable without breakage.

**Comment by Tathanen** [comment]
Well, you applied a fix which is a patch, sure.  But changing the queryUrl signature is arguably minor-worthy.

**Comment by Tathanen** [comment]
Don't forget to update the signature in the link to that section.  And put the 5.1.0 or 5.0.1 in package.json.

**Comment by jrit** [comment]
readme is updated.

In my experience, the way these kinds of fixes for fundamentally broken releases are versioned are as patches

**Comment by Tathanen** [comment]
AND put square brackets around options in the doc since it's optional!!!

**Comment by jrit** [comment]
done!!!!

**Comment by Tathanen** [comment]
You still need it on like 157 in the readme!!!

**Comment by scottferg** [comment]
SHUT UP

**Comment by jrit** [comment]
These docs are difficult to maintain

**Comment by Tathanen** [comment]
LGTM :+1:

**Comment by scottferg** [comment]
Hey who changed my comment

**Pull request merged**
