### PR TITLE
Disable authentication functions for a set of routes

### PR DESCRIPTION
**Pull request by Tathanen**
@vokal/web Kinda wish I had thought of this earlier today, but oh well.  Non-breaking, allows you to whitelist specific API routes against the authentication functionality, not just a specific page.  Lets you use it on sites where login could be in the header, a lightbox, or generally anyplace.

### CODE REVIEW

**Comment by Tathanen** [comment]
@vokal/web anybody?

**Comment by dmaloneycalu** [comment]
Logic/code looks fine, anyone else for approval?

**Comment by jrit** [comment]
I think the last PR was merged and breaking so this should be v6->v7, not a minor. Your message here says non-breaking, but this would still be the first breaking release. Right?

**Comment by Tathanen** [comment]
I already released v6 before this, so no.

**Comment by jrit** [comment]
got it, missed the release

**Comment by Tathanen** [comment]
K, sounds like we're all good here.  Will morge/release.

**Pull request merged**
