### PR TITLE
Remove unnecessary repetition

### PR DESCRIPTION
**Pull request by dmaloneycalu**
@Tathanen v4.0.2

Was the version removed from the package file?

### CODE REVIEW

**Comment by Tathanen** [comment]
I think it was removed since we aren't publishing on npm.  Less stuff to maintain. 

LGTM.  Did Jarrett teach you how to make  .x releases work?

**Comment by dmaloneycalu** [comment]
It's just creating a new release through the Repo, can do.

**Comment by Tathanen** [comment]
Well he does like two releases then deletes one or some wild crap, one that's  .0.2 and one that's .0.x. It's weird.

**Comment by dmaloneycalu** [comment]
I'll wait then and discuss with him when he's back. There's no rush here.

**Comment by jrit** [comment]
With the release, after publishing the normal v4.0.2 release, you can also publish a v4.0.x release and then as soon as it is published, delete the release, which will leave the tag. I don't know a better way to create a tag on github.com, though you could also make the tag directly in git, but then you have to push/merge to get it into master, I think. That said, I'm not sure anyone was actually using any 4.0.x release of the api, I think that was mostly just on dominatr-grunt.

**Comment by dmaloneycalu** [comment]
Going to merge this and create a release, will talk to @jrit if anything goes wildly wrong.

**Comment by dmaloneycalu** [comment]
@jrit Both `4.0.x` and `4.x` resolve to 4.0.2, I don't see a need to create a 4.0.x release and then delete it to keep the tag here.

**Comment by jrit** [comment]
Are you talking about bower or npm? They work differently. Sounds like you mean bower.

**Comment by dmaloneycalu** [comment]
Yes, I was testing this with Bower since it's being included as a Bower dependency

**Comment by jrit** [comment]
Then it isn't a concern until we start installing deps with npm

**Pull request merged**
