### PR TITLE
Support resolution of authentication issues

### PR DESCRIPTION
**Pull request by Tathanen**
@vokal/web soooo this ended up way more elaborate than I had originally planned.  Lemme know what ya'll think.

I don't actually know if it works, though, since I haven't been able to write any tests yet.  I tried to run the tests as they were, and was met with a whole mess of errors.  Would one of you mind running the tests on the main fork and letting me know if they pass?  It'll let me know if it's something I broke, or if maybe it's just new versions of packages breaking things or something.

Will get tests added to this PR one way or another before expecting it to be merged.

### CODE REVIEW

**Comment by CMDadabo** [comment]
I wasn't able to get them to run in the main fork either. Maybe I don't understand how they're supposed to work, but it looks like `karma.conf.js` is referencing a bunch of files that don't exist, namely:
```
            "source/components/angular/angular.js",
            "source/components/angular-mocks/angular-mocks.js",
            "source/components/humps/humps.js",
```

I don't see how the tests would run without Angular being included somewhere. Right now, PhantomJS fails for me with this error:
```
ReferenceError: Can't find variable: angular
  at /Users/christophermdadabo/github/vokal-ng-api/source/services-API.js:6
```

which makes sense to me, because I don't see Angular anywhere.

**Comment by Tathanen** [comment]
Well, you gotta run npm install and bower install first.  The angular files come from bower.

**Comment by CMDadabo** [comment]
Thanks, totally forgot about bower...

**Comment by CMDadabo** [comment]
Tests run in the main fork.

**Comment by Tathanen** [comment]
Hm!  Okay thanks, that is helpful.  Let's see what I bunged up in here.

**Comment by jrit** [comment]
maybe remove bower? maybe?

**Comment by Tathanen** [comment]
WELL I'm using bower to install it for medline, so no.  But I'll move the dev dependencies from bower to npm at least.

**Comment by jrit** [comment]
Works for me

**Comment by Tathanen** [comment]
Looks like the test issue was old-ass npm dependencies that didn't work with angular 1.5.  So got that fixed, will actually write tests now.

**Comment by Tathanen** [comment]
@vokal/web okay this should be good to actually look at now!

**Comment by Tathanen** [comment]
@jrit poke

**Comment by dmaloneycalu** [comment]
@Tathanen is this a priority? I'd like to take a look at it but am occupied with ATI since this is "feature complete" week

**Comment by Tathanen** [comment]
I'd like to get it in early this week, so I can move a Medline story to done.

**Comment by jrit** [comment]
I'm not seeing a change log indicating whatever is a breaking change in here, can you add? I don't see any problems, but logic is a bit complicated. LGTM overall

**Comment by Tathanen** [comment]
We haven't been maintaining a changelog file prior to this, do you think we need one?  I feel like the release notes are a good place for that.  I can draft a release with a list of the changes.

**Pull request merged**
